### ISSUE TITLE
problem of the form to obtain Dataset & Assets

### ISSUE THREAD

**Issue by Student-of-Holmes** [PKU-EPIC/PartManip#3]
Hello, thank you for your incredible work!

I've been attempting to replicate the demo example lately. Unfortunately, the Google form for obtaining the Dataset&Assets seems to be malfunctioning. It doesn't allow me to input my name, affiliation, and other details in the answer frame.

I was wondering if you could fix the form, or if it's possible, I would greatly appreciate it if you could directly send me the Dataset to my email.

Here's my email brucelee@bupt.edu.cn

**Comment by geng-haoran** [comment]
already sent

**Comment by jaredmejia** [comment]
@geng-haoran I'm having a problem where the link to the Assets included in the google form doesn't seem to be working anymore, would you be able to send me the dataset as well? My email is jamejia@cs.cmu.edu

**Comment by geng-haoran** [comment]
Thank you so much for pointing out the problem and I will update it as soon as possible.

**Comment by geng-haoran** [comment]
@jaredmejia, the Problem has already been solved, please refill the form and get the new link.

**Comment by jaredmejia** [comment]
@geng-haoran hmm the link still doesn't seem to be working on my end. [Here](https://www.google.com/url?q=https://drive.google.com/file/d/16fK56sXCYu3xpKVVV5DbGtuRK77zgKLR/view?usp%3Dshare_link&sa=D&source=editors&ust=1693779380391734&usg=AOvVaw3eLWf1xynv92Ncu-z8DkFX) is the link to the assets included in the form after I filled out again. It looks like the same as the link last time I filled it out. Has the link on the form been updated yet?

**Comment by geng-haoran** [comment]
It seems there is a problem with the link update. I fixed it. please try again.

**Comment by jaredmejia** [comment]
@geng-haoran Works for me now, thanks for the help!
